### ISSUE TITLE
How to add external module

### ISSUE THREAD

**Issue by bitbaggi** [LayZeeDK/ngx-ivy-minimal-elements-without-platform-and-ngzone#1]
Hi There,

i tried to clone this repository and add two external libs.
"chart.js" version 2.9.3 and "ng2-charts" version 2.3.0

With a normal angular app, you have to import the ChartsModule to app.module.ts

How I have to add the modules without an app.module.ts like this project?

Do you have any answers for me?

Here is my Repository : https://gitlab.com/bitbaggi/charts-js-component

**Comment by LayZeeDK** [comment]
Hi @bitbaggi,

I just created a repository using this technique with more than just one component:
https://github.com/LayZeeDK/ngx-ivy-zippy-elements-without-platform-and-ngzone

It uses a feature render module to support AOT compilation. Component render modules can also be used but only work with JIT compilation. We might be able to just use SCAMs, but I prefer to declare and reference as few Angular modules as possible.

I explain render modules and SCAMs in my talk [Angular Revisited: Tree-shakable Components and Optional NgModules](https://youtu.be/DA3efofhpq4).

I explain SCAMs in my article [Emulating tree-shakable components using single component Angular modules](https://indepth.dev/emulating-tree-shakable-components-using-single-component-angular-modules/).

Both SCAMs and the two variants of render modules are also able to import other modules, for example from 3rd party package dependencies.
